# Issue Intercepting Postgres Data

**Problem 1:** Strace shows that the connection with FD=9 is closed before data is sent/received on it why?

**Answer:** Because postgres is multi-process arch and it hands off that FD to another process after connection.

File descriptors are per-process resources. Closing an FD in one process does not close it in another. What you’re seeing in strace is the parent process closing its copy of FD=9, followed by the child process using FD=9 for I/O operations after the parent’s close.

**Code change:** Stop deleting connections in the SocketMap on the CloseEvent - I'm not even sure why we needed this event in the first place? But all tests are passing without it, including the load tests.

```
accept(5, {sa_family=AF_INET, sin_port=htons(37928), sin_addr=inet_addr("172.17.0.3")}, [128 => 16]) = 9
strace: Process 7878 attached
[pid  7683] close(9)                    = 0
[pid  7878] close(10)                   = 0
[pid  7878] close(4)                    = 0
[pid  7878] close(5)                    = 0
[pid  7878] close(6)                    = 0
[pid  7878] close(7)                    = 0
[pid  7878] recvfrom(9, "\0\0\0f\0\3\0\0user\0postgres\0datestyle\0"..., 8192, 0, NULL, NULL) = 102
[pid  7878] close(5)                    = 0
[pid  7878] close(5)                    = 0
[pid  7878] sendto(9, "R\0\0\0\27\0\0\0\nSCRAM-SHA-256\0\0", 24, 0, NULL, 0) = 24
[pid  7878] recvfrom(9, "p\0\0\0>SCRAM-SHA-256\0\0\0\0(n,,n=post"..., 8192, 0, NULL, NULL) = 63
[pid  7878] sendto(9, "R\0\0\0\\\0\0\0\vr=KIh/bsDp92IA4BZzDdLq5"..., 93, 0, NULL, 0) = 93
[pid  7878] recvfrom(9, 0xaaaad65b4bc8, 8192, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
[pid  7878] recvfrom(9, "p\0\0\0lc=biws,r=KIh/bsDp92IA4BZzDd"..., 8192, 0, NULL, NULL) = 109
[pid  7878] close(5)                    = 0
[pid  7878] close(5)                    = 0
[pid  7878] close(20)                   = 0
[pid  7878] close(20)                   = 0
[pid  7878] sendto(8, "\30\0\0\0\f\0\0\0\2775\0\0", 12, 0, NULL, 0) = 12
[pid  7878] sendto(8, "\2\0\0\0\300\3\0\0\2775\0\0\10\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 960, 0, NULL, 0) = 960
[pid  7878] sendto(8, "\2\0\0\0\220\1\0\0\2775\0\0\3\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 400, 0, NULL, 0) = 400
[pid  7878] sendto(8, "\2\0\0\0P\3\0\0\0\0\0\0\7\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 848, 0, NULL, 0) = 848
[pid  7878] sendto(8, "\20\0\0\0H\0\0\0\6\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0"..., 72, 0, NULL, 0) = 72
[pid  7878] sendto(9, "R\0\0\0006\0\0\0\fv=IKMa7BTIHJknEltdTDxYX"..., 472, 0, NULL, 0) = 472
[pid  7878] recvfrom(9, 0xaaaad65b4bc8, 8192, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
[pid  7878] recvfrom(9, "Q\0\0\0\6;\0", 8192, 0, NULL, NULL) = 7
[pid  7878] sendto(9, "I\0\0\0\4Z\0\0\0\5I", 11, 0, NULL, 0) = 11
[pid  7878] recvfrom(9, "Q\0\0\0=SELECT id, name, quantity, "..., 8192, 0, NULL, NULL) = 62
[pid  7878] sendto(9, "T\0\0\0\202\0\5id\0\0\0@\1\0\1\0\0\0\27\0\4\377\377\377\377\0\0name"..., 349, 0, NULL, 0) = 349
[pid  7878] recvfrom(9, "X\0\0\0\4", 8192, 0, NULL, NULL) = 5
[pid  7878] sendto(8, "\31\0\0\0\20\0\0\0\2775\0\0\1\0\0\0", 16, 0, NULL, 0) = 16
[pid  7878] sendto(8, "\2\0\0\0\300\3\0\0\2775\0\0\10\0\0\0\2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 960, 0, NULL, 0) = 960
[pid  7878] sendto(8, "\2\0\0\0\300\3\0\0\2775\0\0\10\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 960, 0, NULL, 0) = 960
[pid  7878] sendto(8, "\2\0\0\0\220\1\0\0\2775\0\0\3\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 400, 0, NULL, 0) = 400
[pid  7878] sendto(8, "\2\0\0\0 \1\0\0\0\0\0\0\2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 288, 0, NULL, 0) = 288
[pid  7878] sendto(8, "\20\0\0\0H\0\0\0\6\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0"..., 72, 0, NULL, 0) = 72
[pid  7878] +++ exited with 0 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=104, si_uid=105, si_status=0, si_utime=1, si_stime=1} ---
```

**Problem 2:** Postgres PID changes between connect and data events

**Answer:** Because postgres is spawning a new process with which to do the query.

**Code Change**: Tried using kprobe/clone & kprobe/kernel_clone but both give the PID in the container namesapce and not the host namespace. Instead used tracepoint which works perfectly.

```
) = 1 (in [5], left {tv_sec=47, tv_nsec=535483729})
rt_sigprocmask(SIG_SETMASK, ~[ILL TRAP ABRT BUS FPE SEGV CONT SYS RTMIN RT_1], NULL, 8) = 0
accept(5, {sa_family=AF_INET, sin_port=htons(47946), sin_addr=inet_addr("172.17.0.2")}, [128 => 16]) = 9
getsockname(9, {sa_family=AF_INET, sin_port=htons(5432), sin_addr=inet_addr("172.17.0.3")}, [128 => 16]) = 0
setsockopt(9, SOL_TCP, TCP_NODELAY, [1], 4) = 0
setsockopt(9, SOL_SOCKET, SO_KEEPALIVE, [1], 4) = 0
getpid()                                = 62
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLDstrace: Process 126 attached
, child_tidptr=0x7d655b600d10) = 126
[pid   126] set_robust_list(0x7d655b600d20, 24 <unfinished ...>
[pid    62] close(9 <unfinished ...>
[pid   126] <... set_robust_list resumed>) = 0
[pid    62] <... close resumed>)        = 0
[pid    62] rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
[pid    62] pselect6(8, [5 6 7], NULL, NULL, {tv_sec=60, tv_nsec=0}, NULL <unfinished ...>
[pid   126] openat(AT_FDCWD, "/proc/self/oom_score_adj", O_WRONLY) = 10
```
